In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
# basic data analysis and cleaning

#loading dataset
#checking is there is any missing values or errors
#check datatypes
#number of row and columns or shape
#find duplicates , and how many number of dup is present then remove duplicates
#summary statistics for numerical columns

In [87]:
# loading dataset
df = pd.read_csv('/Users/thameem/Desktop/thameem/Machine Learning/Data/messy_data.csv')

In [88]:
df.shape

(51, 9)

In [89]:
# checking number of missing value or nan value present
df.isnull().sum()

id             0
name           0
age            7
gender         0
city           2
salary         2
experience     2
department     1
date_joined    1
dtype: int64

In [90]:
# removing othe null value with integer 0
df = df.fillna(0)
df.isnull().sum()

id             0
name           0
age            0
gender         0
city           0
salary         0
experience     0
department     0
date_joined    0
dtype: int64

In [91]:
# datatype information of each column in dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           51 non-null     int64
 1   name         51 non-null     str
 2   age          51 non-null     float64
 3   gender       51 non-null     str
 4   city         51 non-null     object
 5   salary       51 non-null     float64
 6   experience   51 non-null     float64
 7   department   51 non-null     object
 8   date_joined  51 non-null     object
dtypes: float64(3), int64(1), object(3), str(2)
memory usage: 3.7+ KB

In [92]:
# finding duplicated row
df_dup = df[df.duplicated()]
print(df_dup)

    id    name   age gender   city   salary  experience department date_joined
48  48  Sameer  28.0      M  Delhi  58000.0         3.0         HR  2022-05-05

In [93]:
# number of duplicated data in this dataset
total_dup = df.duplicated().sum()
print(total_dup)

1

In [94]:
# removing the duplicate rows
df = df.drop_duplicates()
total_dup = df.duplicated().sum()
print(total_dup)

0

In [95]:
# summary statistics
df.describe()

             id        age        salary  experience
count  50.00000  50.000000      50.00000   50.000000
mean   25.50000  27.720000   67360.00000    6.760000
std    14.57738  12.424531   21157.09945    4.340413
min     1.00000   0.000000       0.00000    0.000000
25%    13.25000  26.250000   58250.00000    3.250000
50%    25.50000  30.000000   69000.00000    6.000000
75%    37.75000  35.000000   78000.00000    9.000000
max    50.00000  45.000000  120000.00000   20.000000

In [96]:
# analysis on each column

# updating missing values and rows based on the importance 
# updating missing age, salary with mean of entire column
# removind unwanted columns
# standardizing the male and female
# detect outliers
# convert all date

In [97]:
# updating a column for a specific row based on importance of that column
df[df['date_joined']==0]

   id name   age gender    city   salary  experience department date_joined
8   9  Ian  31.0      M  Mumbai  72000.0         6.0         IT           0

In [98]:
# finding the joined date with experience
# the current date - year of experience
# 2026 - 6 = 2020-03-26
df[df['date_joined']==0]

   id name   age gender    city   salary  experience department date_joined
8   9  Ian  31.0      M  Mumbai  72000.0         6.0         IT           0

In [99]:
df.iloc[8,8] = '2020-03-26'

In [100]:
df.iloc[8]

id                      9
name                  Ian
age                  31.0
gender                  M
city               Mumbai
salary            72000.0
experience            6.0
department             IT
date_joined    2020-03-26
Name: 8, dtype: object

In [101]:
# now updating column age and salary 
df[df['age']==0]

,id,name,age,gender,city,salary,experience,department,date_joined
2,3,Charlie,0.0,M,Bangalore,70000.0,7.0,IT,2019-07-20
7,8,Helen,0.0,F,Delhi,62000.0,4.0,Finance,2021-06-18
13,14,Mia,0.0,F,Mumbai,65000.0,5.0,IT,2020-12-12
20,21,Tom,0.0,M,Chennai,60000.0,5.0,IT,2021-03-03
27,28,Amit,0.0,M,Delhi,54000.0,3.0,HR,2022-05-05
34,35,Fiona,0.0,F,Chennai,72000.0,7.0,Finance,2018-03-03
41,42,Manoj,0.0,M,Bangalore,65000.0,6.0,IT,2019-11-11

In [102]:
# treating zero as nan value 
df['age'] = df['age'].replace(0, np.nan)

In [103]:
df.iloc[2]

id                      3
name              Charlie
age                   NaN
gender                  M
city            Bangalore
salary            70000.0
experience            7.0
department             IT
date_joined    2019-07-20
Name: 2, dtype: object

In [104]:
mean_age = df['age'].mean()

In [105]:
df['age'] = df['age'].fillna(mean_age,  inplace=True)

/var/folders/d0/0z7mg03d4zggp6_2nq04bd280000gn/T/ipykernel_57054/1854742288.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'] = df['age'].fillna(mean_age,  inplace=True)

In [106]:
df['age'] = df['age'].astype(int)
df.head()

,id,name,age,gender,city,salary,experience,department,date_joined
0,1,Alice,25,F,Delhi,50000.0,2.0,HR,2021-05-01
1,2,Bob,30,M,Mumbai,60000.0,5.0,IT,2020-03-15
2,3,Charlie,32,M,Bangalore,70000.0,7.0,IT,2019-07-20
3,4,David,29,M,0,80000.0,6.0,Finance,2018-01-10
4,5,Eva,35,F,Delhi,0.0,10.0,HR,2017-09-23

In [107]:
# now fixing the column salary with mean
df[df['salary']==0]

    id name  age gender    city  salary  experience department date_joined
4    5  Eva   35      F   Delhi     0.0        10.0         HR  2017-09-23
21  22  Uma   37      F  Mumbai     0.0        11.0         HR  2014-02-02

In [108]:
df['salary'] = df['salary'].replace(0, np.nan)

In [109]:
df['salary'] = df['salary'].fillna(df['salary'].mean())

In [110]:
df['salary'] = df['salary'].astype(int)
df.head()

,id,name,age,gender,city,salary,experience,department,date_joined
0,1,Alice,25,F,Delhi,50000,2.0,HR,2021-05-01
1,2,Bob,30,M,Mumbai,60000,5.0,IT,2020-03-15
2,3,Charlie,32,M,Bangalore,70000,7.0,IT,2019-07-20
3,4,David,29,M,0,80000,6.0,Finance,2018-01-10
4,5,Eva,35,F,Delhi,70166,10.0,HR,2017-09-23

In [111]:
# remaining task 

# fill the empty department column based on salary range and experience
'''
High salary + high experience → IT / Finance
Low salary + low experience → HR
Mid combos → mixed

'''

'\nHigh salary + high experience → IT / Finance\nLow salary + low experience → HR\nMid combos → mixed\n\n'

In [112]:
df[df['department']==0]

    id  name  age gender    city  salary  experience department date_joined
42  43  Nina   33      F  Mumbai   73000         8.0          0  2018-12-12

In [113]:
# Creating groups using BOTH features
df['salary_grp'] = pd.qcut(df['salary'], q=3, labels=['low', 'medium', 'high'])
df['experience_grp'] = pd.qcut(df['experience'], q=3, labels=['junior', 'mid_exp', 'senior'])

In [114]:
#treating the zero in department as nan value

df['department'] = df['department'].replace(0, np.nan)

In [115]:
#now filling the department column based on new columns salary_grp and exp_grp

df['department'] = df['department'].fillna(
    df.groupby(['salary_grp', 'experience_grp'])['department']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

In [116]:
# now checking the row where department was zero 
df.iloc[42]

id                        43
name                    Nina
age                       33
gender                     F
city                  Mumbai
salary                 73000
experience               8.0
department           Finance
date_joined       2018-12-12
salary_grp              high
experience_grp       mid_exp
Name: 42, dtype: object

In [117]:
# now droping the new columns 
df.drop(['salary_grp','experience_grp'], axis=1, inplace=True)

In [118]:
# filling city with mode based on department

# finding how many city got missing here
df[df['city']==0]

    id   name  age gender city  salary  experience department date_joined
3    4  David   29      M    0   80000         6.0    Finance  2018-01-10
14  15   Noah   38      M    0   85000        12.0    Finance  2015-05-05

In [119]:
# treating zero as nan 

df['city'] = df['city'].replace(0, np.nan)
df['city'].head()

0        Delhi
1       Mumbai
2    Bangalore
3          NaN
4        Delhi
Name: city, dtype: object

In [120]:
# now filling with mode 
df['city'] = df['city'].fillna(
    df.groupby('department')['city']
    .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)
df['city'].head()

0        Delhi
1       Mumbai
2    Bangalore
3       Mumbai
4        Delhi
Name: city, dtype: object

In [121]:
df.head(10)

,id,name,age,gender,city,salary,experience,department,date_joined
0,1,Alice,25,F,Delhi,50000,2.0,HR,2021-05-01
1,2,Bob,30,M,Mumbai,60000,5.0,IT,2020-03-15
2,3,Charlie,32,M,Bangalore,70000,7.0,IT,2019-07-20
3,4,David,29,M,Mumbai,80000,6.0,Finance,2018-01-10
4,5,Eva,35,F,Delhi,70166,10.0,HR,2017-09-23
5,6,Frank,40,M,Mumbai,90000,0.0,IT,2016-11-11
6,7,Grace,28,F,Bangalore,55000,3.0,HR,2022-02-14
7,8,Helen,32,F,Delhi,62000,4.0,Finance,2021-06-18
8,9,Ian,31,M,Mumbai,72000,6.0,IT,2020-03-26
9,10,Jack,27,M,Bangalore,58000,3.0,HR,2022-08-09